### ISSUE TITLE
Application Server Embeded

### ISSUE THREAD

**Issue by hendisantika** [hupadhyay/springmvc_helloworld#2]
Hi Hupad,
I already clone the recent repo.

Could you add some embeded Application Server (tomcat plug-in / jetty) on your repo?
So that I can run it.

I am still having error when running it.

I use following command :
mvn clean tomcat7:run

**Comment by hupadhyay** [comment]
Maven tomcat7 plugin is not updated for long time. It doesn't support 1.8. Please deploy war file to tomcat server.

http://www.codejava.net/servers/tomcat/how-to-deploy-a-java-web-application-on-tomcat
